# project definitions
project: guide
audience: designers
product: all
platform: all
version: all
output: web
destination: _site
topnav_title: http://guide.openrif.org
homepage_title: The OpenRIF Guide
site_title: OpenRIFGuide
project_folder: guide
company_name: openrif.org
footer_image_location: ../common_images/company_logo.png
github_editme_path: https://github.com/openrif/guide.openrif.org/edit/gh-pages
disqus_shortname: openrif
# variables


#sidebar_tagline: Designers
#sidebar_version: Version 4.0
theme_file: theme-blue.css
#pdf_file_name: mydoc_designers_pdf.pdf

# the algolia entries here are experimental only.

#gems:
#  - algoliasearch-jekyll
#algolia:
#  application_id: 'HXUBJERYYB'
#  index_name:     'documentation_theme_jekyll_designers'
port: 40011

exclude:
  - _site
  - _drafts
  - configs/
  - mydoc/
  - mydoc_*

# same for all
host: 127.0.0.1
#feedback_email: tomjohnson1492@gmail.com

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true

collections:
  tooltips:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      search: true
      tooltip: true

